id: flow_execution_outputs
namespace: company.team

tasks:
  - id: hello
    type: io.kestra.plugin.core.log.Log
    message: Triggered only when upstream row_count > 0!

triggers:
  - id: after_extract
    type: io.kestra.plugin.core.trigger.Flow
    dependsOn:
      - flowId: extract
        namespace: company.team
        when: "{{ outputs.row_count > 0 }}"
        states: [SUCCESS]
