id: flow_preconditions_where
namespace: company.team

tasks:
  - id: hello
    type: io.kestra.plugin.core.log.Log
    message: Triggered by matching namespace and label filter!

triggers:
  - id: listen
    type: io.kestra.plugin.core.trigger.Flow
    dependsOn:
      - when: "{{ (trigger.namespace startsWith 'io.kestra.tests') and (labels.some == 'label') }}"
