id: schedule-condition-timebetween
namespace: sanitychecks
tasks:
  - id: hello
    type: io.kestra.plugin.core.log.Log
    message: Demo for TimeBetween condition
triggers:
  - id: schedule
    type: io.kestra.plugin.core.trigger.Schedule
    cron: "@hourly"
    when: "{{ hourOfDay(trigger.date) >= 8 and hourOfDay(trigger.date) < 17 }}"
